### ISSUE TITLE
Local installed ev-cli tool can break the Yocto build

### ISSUE THREAD

**Issue by mhei** [EVerest/meta-everest#26]
When developing on EVerest itself, it might happen that one has newer ev-cli versions in the local development environment available. Then when doing a local Yocto build with EVerest, and when the newer tool is not compatible (anymore) with the EVerest version in the Yocto build, then the Yocto build fails e.g. due to wrong generated code.

Within the Yocto build itself, it should be ensured that only ev-cli is used from inside the Yocto build process.

**Comment by dvileta** [comment]
Seems we are having this problem too:


```

| CMake Error at cmake/ev-cli.cmake:21 (message):
|   ev-cli version 0.1.0 or higher is required.  However your ev-cli version is
|   '0.0.24'.  Please upgrade ev-cli.
| Call Stack (most recent call first):
|   cmake/ev-project-bootstrap.cmake:8 (require_ev_cli_version)
|   CMakeLists.txt:102 (include)
| 
|
| -- Configuring incomplete, errors occurred!
```

**Comment by mhei** [comment]
Meanwhile, `ev-cli` is (or at least can be) used during the build with a Python venv which solves this issue by design. I'm too lazy to look for the exact revision/commit to reference it here. I think, we can close this issue, so I'm doing. Please re-open if there is still trouble out there.
